add resource.infer(stats=True) as workaround
I'm getting the following error trying to this during resource transformation pipeline

│   164 │   │   # Create missing value                                                             │
│   165 │   │   try:                                                                               │
│ ❱ 166 │   │   │   missing_value = self.missing_values[0]                                         │
│   167 │   │   │   if not self.has_defined("missing_values") and self.schema:                     │
│   168 │   │   │   │   missing_value = self.schema.missing_values[0]                              │
│   169 │   │   except IndexError:                                                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: 'NoneType' object is not subscriptable
make: *** [data/indicadores_planejamento.csv] Error 1