Adiciona custom steps para transformações (#17)
* adiciona custom steps para frictionless transform pipeline

* bump dev version

* move data folder to tests directory

* add tests to field_rename_to_target

* add NA as missingValue for uo_desc field

* add tests to table_write_normalized

* remove step enrich_resource

* add docstrings

* bump dev version

* add output_dir argument to table_write_normalized

* bump dev version

* fix bug during setup of resource.path in table_write_normalized

* bump dev version

* resource.path should be string not pathlib.Path

* bump dev version

* add resource.infer(stats=True) as workaround

I'm getting the following error trying to this during resource transformation pipeline

│   164 │   │   # Create missing value                                                             │
│   165 │   │   try:                                                                               │
│ ❱ 166 │   │   │   missing_value = self.missing_values[0]                                         │
│   167 │   │   │   if not self.has_defined("missing_values") and self.schema:                     │
│   168 │   │   │   │   missing_value = self.schema.missing_values[0]                              │
│   169 │   │   except IndexError:                                                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: 'NoneType' object is not subscriptable
make: *** [data/indicadores_planejamento.csv] Error 1

* adiciona assertion para reproduzir bug #19

* adiciona reprex para issue splor-mg/obz-dados#2

* field_rename_to_target atribui etl table com headers corretos para resource.data

* bump dev version

* fix urls of reprex repo

* reset properties on a field by field basis

Closes #18
Closes #19

---------

Co-authored-by: Andrey Morais Labanca SEPLAG <m7525850@ca.mg.gov.br>