Instalação de repos privados, custom steps e data.yaml (#25)
* auth git private repo with reponses headers

* update pyproject.toml

* testing env var for GITHUB_TOKEN

* acesso a repos privados do github com token de autenticação.

* usando variavel de ambiente no datapackage.yaml

* usando variavel de ambiente no datapackage.yaml

* Corrige erro do os.getenv() quando dicionário source não contêm item 'token' e retornava None

* print da env var e token para debug no docker

* valor do token não deve ser impresso para tela

logs no github por exemplo ficam publicamente acessíveis para repositórios públicos

* refactor update_session_headers

* Armazena dependências em data package data.yaml (#21)

* list data sources in a data package named data.yaml

* pass data.yaml as argument to dpm install

* add --output_dir to dpm install to allow proper testing

* update tests

* dev version v0.0.0.9006

* Adiciona custom steps para transformações (#17)

* adiciona custom steps para frictionless transform pipeline

* bump dev version

* move data folder to tests directory

* add tests to field_rename_to_target

* add NA as missingValue for uo_desc field

* add tests to table_write_normalized

* remove step enrich_resource

* add docstrings

* bump dev version

* add output_dir argument to table_write_normalized

* bump dev version

* fix bug during setup of resource.path in table_write_normalized

* bump dev version

* resource.path should be string not pathlib.Path

* bump dev version

* add resource.infer(stats=True) as workaround

I'm getting the following error trying to this during resource transformation pipeline

│   164 │   │   # Create missing value                                                             │
│   165 │   │   try:                                                                               │
│ ❱ 166 │   │   │   missing_value = self.missing_values[0]                                         │
│   167 │   │   │   if not self.has_defined("missing_values") and self.schema:                     │
│   168 │   │   │   │   missing_value = self.schema.missing_values[0]                              │
│   169 │   │   except IndexError:                                                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: 'NoneType' object is not subscriptable
make: *** [data/indicadores_planejamento.csv] Error 1

* adiciona assertion para reproduzir bug #19

* adiciona reprex para issue splor-mg/obz-dados#2

* field_rename_to_target atribui etl table com headers corretos para resource.data

* bump dev version

* fix urls of reprex repo

* reset properties on a field by field basis

Closes #18
Closes #19

---------

Co-authored-by: Andrey Morais Labanca SEPLAG <m7525850@ca.mg.gov.br>

---------

Co-authored-by: labanca <moraislabanca@gmail.com>
Co-authored-by: Andrey Morais Labanca SEPLAG <m7525850@ca.mg.gov.br>